<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.0.3 setup script
 * Date: Fri, 08 May 2015 09:15:43 -0700
 */

/* Servers configuration */
$i = 0;

/* Server: phtel [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'phtel';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['blowfish_secret'] = '554ce0590fe8b3.70825088';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>